service: slackbot-imgdesc

provider:
  name: aws
  runtime: nodejs6.10

functions:
  event:
    handler: handler.handler
    events:
      - http:
          path: /
          method: POST
    environment:
      variable2: value2
